version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: geodb
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d geodb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: . # Build from the current directory
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app # Mount the current directory to the container's /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/geodb"